package br.com.tellescom.domain;

import static br.com.tellescom.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class AcaoCriticaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAcaoCriticaAllPropertiesEquals(AcaoCritica expected, AcaoCritica actual) {
        assertAcaoCriticaAutoGeneratedPropertiesEquals(expected, actual);
        assertAcaoCriticaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAcaoCriticaAllUpdatablePropertiesEquals(AcaoCritica expected, AcaoCritica actual) {
        assertAcaoCriticaUpdatableFieldsEquals(expected, actual);
        assertAcaoCriticaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAcaoCriticaAutoGeneratedPropertiesEquals(AcaoCritica expected, AcaoCritica actual) {
        assertThat(expected)
            .as("Verify AcaoCritica auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAcaoCriticaUpdatableFieldsEquals(AcaoCritica expected, AcaoCritica actual) {
        assertThat(expected)
            .as("Verify AcaoCritica relevant properties")
            .satisfies(e -> assertThat(e.getAcaoCritica()).as("check acaoCritica").isEqualTo(actual.getAcaoCritica()))
            .satisfies(e -> assertThat(e.getNomeResponsavel()).as("check nomeResponsavel").isEqualTo(actual.getNomeResponsavel()))
            .satisfies(e -> assertThat(e.getIdResponsavel()).as("check idResponsavel").isEqualTo(actual.getIdResponsavel()))
            .satisfies(e -> assertThat(e.getDataAcao()).as("check dataAcao").isEqualTo(actual.getDataAcao()))
            .satisfies(e -> assertThat(e.getInstrucaoAcao()).as("check instrucaoAcao").isEqualTo(actual.getInstrucaoAcao()))
            .satisfies(e -> assertThat(e.getIdIndicadorCritica()).as("check idIndicadorCritica").isEqualTo(actual.getIdIndicadorCritica()))
            .satisfies(e ->
                assertThat(e.getCriadoEm()).as("check criadoEm").usingComparator(zonedDataTimeSameInstant).isEqualTo(actual.getCriadoEm())
            )
            .satisfies(e ->
                assertThat(e.getAtualizadoEm())
                    .as("check atualizadoEm")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getAtualizadoEm())
            )
            .satisfies(e -> assertThat(e.getIsNotificado()).as("check isNotificado").isEqualTo(actual.getIsNotificado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAcaoCriticaUpdatableRelationshipsEquals(AcaoCritica expected, AcaoCritica actual) {
        assertThat(expected)
            .as("Verify AcaoCritica relationships")
            .satisfies(e -> assertThat(e.getIndicadorCritica()).as("check indicadorCritica").isEqualTo(actual.getIndicadorCritica()));
    }
}
