package br.com.tellescom.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IndicadorCriticaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndicadorCriticaAllPropertiesEquals(IndicadorCritica expected, IndicadorCritica actual) {
        assertIndicadorCriticaAutoGeneratedPropertiesEquals(expected, actual);
        assertIndicadorCriticaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndicadorCriticaAllUpdatablePropertiesEquals(IndicadorCritica expected, IndicadorCritica actual) {
        assertIndicadorCriticaUpdatableFieldsEquals(expected, actual);
        assertIndicadorCriticaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndicadorCriticaAutoGeneratedPropertiesEquals(IndicadorCritica expected, IndicadorCritica actual) {
        assertThat(expected)
            .as("Verify IndicadorCritica auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndicadorCriticaUpdatableFieldsEquals(IndicadorCritica expected, IndicadorCritica actual) {
        assertThat(expected)
            .as("Verify IndicadorCritica relevant properties")
            .satisfies(e -> assertThat(e.getIdIndicadorMeta()).as("check idIndicadorMeta").isEqualTo(actual.getIdIndicadorMeta()))
            .satisfies(e -> assertThat(e.getIdPlano()).as("check idPlano").isEqualTo(actual.getIdPlano()))
            .satisfies(e -> assertThat(e.getAnaliseCritica()).as("check analiseCritica").isEqualTo(actual.getAnaliseCritica()))
            .satisfies(e -> assertThat(e.getObservacao()).as("check observacao").isEqualTo(actual.getObservacao()))
            .satisfies(e -> assertThat(e.getMes()).as("check mes").isEqualTo(actual.getMes()))
            .satisfies(e -> assertThat(e.getAno()).as("check ano").isEqualTo(actual.getAno()))
            .satisfies(e -> assertThat(e.getCriadoPor()).as("check criadoPor").isEqualTo(actual.getCriadoPor()))
            .satisfies(e -> assertThat(e.getCriadoEm()).as("check criadoEm").isEqualTo(actual.getCriadoEm()))
            .satisfies(e -> assertThat(e.getAtualizadoPor()).as("check atualizadoPor").isEqualTo(actual.getAtualizadoPor()))
            .satisfies(e -> assertThat(e.getAtualizadoEm()).as("check atualizadoEm").isEqualTo(actual.getAtualizadoEm()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndicadorCriticaUpdatableRelationshipsEquals(IndicadorCritica expected, IndicadorCritica actual) {
        // empty method
    }
}
