package br.com.tellescom.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MetaRecursoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaRecursoAllPropertiesEquals(MetaRecurso expected, MetaRecurso actual) {
        assertMetaRecursoAutoGeneratedPropertiesEquals(expected, actual);
        assertMetaRecursoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaRecursoAllUpdatablePropertiesEquals(MetaRecurso expected, MetaRecurso actual) {
        assertMetaRecursoUpdatableFieldsEquals(expected, actual);
        assertMetaRecursoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaRecursoAutoGeneratedPropertiesEquals(MetaRecurso expected, MetaRecurso actual) {
        assertThat(expected)
            .as("Verify MetaRecurso auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaRecursoUpdatableFieldsEquals(MetaRecurso expected, MetaRecurso actual) {
        assertThat(expected)
            .as("Verify MetaRecurso relevant properties")
            .satisfies(e -> assertThat(e.getRecursoNome()).as("check recursoNome").isEqualTo(actual.getRecursoNome()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaRecursoUpdatableRelationshipsEquals(MetaRecurso expected, MetaRecurso actual) {
        assertThat(expected)
            .as("Verify MetaRecurso relationships")
            .satisfies(e -> assertThat(e.getMetas()).as("check metas").isEqualTo(actual.getMetas()));
    }
}
